### ISSUE TITLE
Data doesn't get downloaded in Safari

### ISSUE THREAD

**Issue by c0debreaker** [AlexLibs/client-side-csv-generator#1]
I tried it with Safari 6.0.4 and the data I entered just gets rendered on the browser after clicking "download csv" button. Also the url gets modified to this

```
data:text/csv;charset=utf-8,ID%2CTitle%2CAmount%2CPrice%0A1%2C1%2C1%2C1%0A%2C%2C%2C%0A%2C%2C%2C
```

**Comment by AlexLibs** [comment]
The library uses _Download attribute_, so it will work only on browsers that support it.

In the Readme (on the main page https://github.com/AlexLibs/client-side-csv-generator) you can find the **Supported browsers** section pointing to the following page: http://caniuse.com/#feat=download

Thank you.
